# Generated by Django 3.2.3 on 2021-05-31 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
    ]
